### ISSUE TITLE
Any plan to prepare for localization ?

### ISSUE THREAD

**Issue by sladecraven** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#11]
Hi !
I am playing the DG game in France, hence i would like to help for localization.
Are you planning to setup the template in the right way to handle localization  in a near future ?

Thanks !

**Comment by TheLastScrub** [comment]
Hey @sladecraven , glad you think the system seems helpful and have interest in helping out.  

This was my first Foundry system (as well as my first web project in a quite a while) and I definitely stumbled my through most of it.  Regrettably one consequence of this is that as you have noticed the system is really not well structured for localization.  

I will see what I can do to get localization working, but it will involve touching all the text in the HTML since I did not have the foresight to build it in to start with.  So it will take some time, I wouldn't expect it to be complete in the near future.  Luckily the system as a whole is not that big, so it may be less work than I'm imagining.

**Comment by TheLastScrub** [comment]
v0.9.4 should have pretty much everything but the compendium pack localized I think... Or at least I made by best attempt.  There is one section for the default character template that has 'Art - Painting' as a default extra skill that I couldn't figure out how to localize due to it being directly in the actor template currently.  I might revisit it later, but for now you can always just delete that skill and then make a new one with the right name.
