### ISSUE TITLE
Dice So Nice Issue

### ISSUE THREAD

**Issue by Agnestorm** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#116]
As the title states, there's an issue with Dice So Nice and Delta Green where when when you roll, the default foundry dice sound effect happens and then the the Dice So Nice roll comes after so it creates a weird, unsatisfying delayed effect.

**Comment by TheLastScrub** [comment]
This should be resolved in v1.4.5. However as a heads up, **that branch is only compatible with Foundry version 12**. Mostly because @jalensailin fixed it as a part of some other v12 related Dice So Nice issues that had cropped up... I'll close this issue for now, but feel free to reopen it or start a new one if an upgrade doesn't seem to fix it.
