### ISSUE TITLE
Error when opening pre-gen character sheet

### ISSUE THREAD

**Issue by Ypnos666** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#120]
v11.315

<img width="306" alt="image" src="https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/79218571/08d9a25f-8780-476e-98df-1d33e61b2805">

**Comment by TheLastScrub** [comment]
Can you give a little more information? I tried it on Foundry v11.315 and I seem to be able to open Agent sheets from the Pregen Agents compendium without any errors. Are you using a language other than English? If so, which one?

**Comment by jalensailin** [comment]
Is this an error preventing you from opening the sheet or simply a warning telling you that you are missing a translation? We need more information to be able to help ya

**Comment by TheLastScrub** [comment]
@jalensailin this warning will pop up if (as the message implies) those translation keys are missing. It's a region-specific issue, we'd need @Ypnos666 to give us more information to remedy their specific case. But I think because this is the way I wrote translating the header buttons:

![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/67403321/33b81c2a-724e-4db6-95c4-3803c12d1579)

If a bilingual player has their Foundry language preference set to a language DG is not translated to (Korean for instance, perhaps in order to have the general Foundry GUI in that language), they might still be happily playing with the DG system in English BUT they will get this warning every single time they open a character sheet.

Considering that, I think I should just change it from an alert to just log it to the console instead. Your thoughts?

**Comment by Ypnos666** [comment]
Hi, sorry for late reply, this went to junk mail.

I am using standard English Foundry, no bilingual options selected.

I have just created a brand new world, using only the DG game system and no modules switched on. The only action I took was to import the Agent pregens from the compendium and then opened a character sheet. I still get the same warning.

It does not prevent me from opening the character sheet, however I do have a question. Am I supposed to have a Luck button I can click as a player on the character sheet? Is this warning preventing the button from appearing? I have never had this working without the warning, so I don't know.

Thanks

**Comment by TheLastScrub** [comment]
Very strange. I am running DG 1.4.4 and Foundry v11.315 (so exact same as you), and do not see any issues with it, even if I import the actors. What does your Foundry host environment look like (Windows/Linux, Electron client or NodeJS or Forge)? And what browser are you using? 

Or if it's not an issue anymore now that you've found the luck button, I can close the bug out? I will make a slight tweak to the code to try to avoid that warning. But if everything (Foundry and DG) are English, don't think it would do anything for you...

**Comment by Ypnos666** [comment]
I may have found the problem. Looked through the settings and the language is actually set to "Latin - Prettier Login Screen", as I had a css mod that makes the login screen look nicer. So while it is English, it's not "standard" standard English, so I'm guessing your code is seeing it as another language.
<img width="497" alt="image" src="https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/79218571/b4e5a55b-f163-405a-83e4-16e42deb1c32">

Sorry for the faulty information!

Regarding the other question, I'm running Foundry in Docker.

Thanks

**Comment by TheLastScrub** [comment]
Ah thanks, yes that would likely cause the issue as if it were any non-translated language choice... I am going to make a change where this issue will be still there (because it will still fail to localize) but it just won't visibly alert about it anymore so it won't be as annoying.

**Comment by TheLastScrub** [comment]
Should be in v1.4.6 when I package and release it.
