### ISSUE TITLE
[ENH] Include Options for uncommon and rare rolls in Roll Card

### ISSUE THREAD

**Issue by Vogliadicone** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#124]
As a Player I would like to speed up the roll process for at least uncommon and maybe also rare rolls. At the moment I right click at the skill and have to choose the type of modifier (+/- 20/40) and press roll.

My expectation would be, that I right click and then can directly click on a button
- Roll +40%
- Roll +20%
- Roll -20%
- Roll -40%
Or Maybe
- Roll +20%
- Roll -20%
- Roll other (with the option to define the exact type of roll)
That would save me a few clicks.

It would also be nice, to see the modified total in the roll card, f.e.
- Roll +40% (99%)
with 1% / 99% as a min / max value (as defined by the rules). But that's not so important.
![DGroll](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/119852651/d8fa3036-ccf3-4cf4-9935-1b3f694b53af)
- Foundry 12.317
- Delta Green 1.4.5

**Comment by TheLastScrub** [comment]
I did something similar for damage rolls in the Troika! system (which are basically chart lookups with modifiers). It can get a little crowded, but isn't particularly hard.

![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/67403321/1bdd7d4e-b9c8-488f-bfe3-afc9e11915c9)

I'm a little confused about the last part, when you modify the roll, does it not already show that in the chat card?

![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/67403321/62f9b9aa-d7db-4fe7-8eb8-e48dea0565c1)

Or do you mean you would prefer the format of the chat card be that it shows the _unadjusted_ target, instead of the adjusted target? I could see where that would be more clear than the current behavior where it is showing the adjusted total, and then has the modifier afterwards just to indicate that isn't the normal target.

Also as a side note, skill targets are capped at 99 but x5 stat targets can go over 100%, it's just that it's considered "inhuman" and follows slightly different rules on what constitutes a crit. Because that dialogue is generic for all percentile tests, might be a little tricky to cap it at 99%, I'd have to look at it. The fact that it doesn't set the floor to 1% when there is a penalty to the roll is a bug.

**Comment by TheLastScrub** [comment]
@Vogliadicone, this is a fairly straightforward addition, so I played around with it a bit and have it looking like the below. Let me know if it more or less is what you were thinking. 

![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/67403321/73ca48b8-ebe8-4a1c-8fc0-a1e7bf6a25da)

I also tried to adjust the logic around skill tests to cap them at 1/99 as long as they aren't inhuman x5 stat tests. And I have changed the way the logic is described so the format is now "Target% (Base Target +/-Modifier%)" to make it more clear what is going on.

![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/67403321/31a6eeb3-08f4-47ba-89d2-b8c4b860ccd5)

**Comment by Vogliadicone** [comment]
Looks good! I would try to make the roll card more minimalistic by putting the skill and the % in one line. Instead of "Modify Target (+/-):" I would only write "Modifier" wth a free text field after. Ideally you can write a placeholder text inside the field ("f.e. +20") that disappears when you type inside the field. Because with the actual design I'm always unsure, if the +20 are added or not. So overall I would design the roll card like this:

Accounting 15/
Modifier [freetext field with grey placeholder text "f.e. +20"]
Roll Mode ["Public Roll", etc]
Roll | -40 | -20 | +20 | +40

But that´s just my personal preference.

**Comment by TheLastScrub** [comment]
I left the +/- dropdown in because it simplifies the parsing logic underneath it. But to make it a little more obvious what the intention is, I made it so you can't enter anything but whole, positive numbers. I think the change is mostly complete, so it'll be in whatever the next package is.

**Comment by TheLastScrub** [comment]
Should be in v1.4.6 when I package and release it.

**Comment by Vogliadicone** [comment]
Thanks, works like a charm! The only thing I'm not totally convinced of is the "20" in the Modify Target field. I think a "0" could be better, because right now the only roll you can't do here directly is an unmodified roll. But again maybe that's just me...

**Comment by TheLastScrub** [comment]
Not sure I follow, this window is specifically for modifying a roll, you should only see it if you shift click or right click on something that is rollable. If you want an unmodified (modifier of 0) roll, you can just (left) click instead.

**Comment by Vogliadicone** [comment]
I know it's specifically for modifying a roll, but right now the only roll that you can't do in this window with just one click is an unmodified one. For a roll with +20 you've got 2 buttons ("Roll" & "+20"). As I said, no big deal, but I would find a "0" in the Modify Target field clearer.

**Comment by TheLastScrub** [comment]
Ah I see, just the UX perspective of it. I think I will leave it at 20% so you get the same logic as before for just clicking 'roll' but I have changed it so that the modifier you punch in is persistent for a given actor, so if you want to set it to 0% it will stay that way for that character.
