### ISSUE TITLE
[ENH] Sort equipment alphabetically & allow manual sorting

### ISSUE THREAD

**Issue by Vogliadicone** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#131]
As a player I would like to see my equipment by default autom. sorted alphabetically. And I would like to be able to sort my equipment manually.
![Weapon-list](https://github.com/user-attachments/assets/0fec4381-7537-42dc-846a-c0738ad44e18)
Right now the equipment is sorted in the order it is added to the character sheet and it is not possible to manually sort it. In a more military oriented campaign like iconoclasts it is sometimes a bit harder to fast access the weapon you wanna use...

- Foundry 12.330
- Delta Green 1.4.6

**Comment by TheLastScrub** [comment]
I've never run a military campaign, although I do own Iconoclasts. I doubt I would allow a civilian agent to have all that stuff on them actively for a lot of reasons, weight being one. Although I'm guessing some of that is in a vehicle or something. But it has been on my todo list to fix the sorting since sometimes the gear list at least can get a bit cluttered. 

The main tricky thing is, because I had on click handlers for rolls tied to most of the text, it's kind of hard to actually drag anything. Unless you know to somewhat unintuitively click in the empty space of the row.

I may need to run this by Jalen and Michael, but my workaround (and also to make it more clear what is actually rollable) is that I have been trying to put in icons for everything that is rollable, and have the click handlers generally more tied to the _icon_ than the text necessarily. This winds up looking like (I flipped the position of the lethality toggle to keep things consistent):

<img width="581" alt="image" src="https://github.com/user-attachments/assets/85e4173a-9c01-4385-954c-0c21d811620d">

And then I've made the _name_ draggable (as in clicking it no longer rolls the skill check). I think I have the sorting logic togglable between manual and alphabetical for each section as well:

<img width="301" alt="image" src="https://github.com/user-attachments/assets/c2ec9ca3-898b-42ca-8f34-df551236af44">

**Comment by Vogliadicone** [comment]
Yeah, the character is the DG contact in the US Army and since all the characters are based in an US army base in Iraq close the Ises, they can get some heavier weapons. Also one of them is mounted on their Humvee.

Clicking on an icon for attack or damage is ok for me. It's like Roll20 handles it as well. See the Screenshot in #133  .
