### ISSUE TITLE
"Luck" is not localized on roll

### ISSUE THREAD

**Issue by Phenomen** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#26]
1. Click on "Roll Luck"

"Luck" should be localized with "DG.Luck" string but it's not.

**Comment by TheLastScrub** [comment]
Hey Phenomen, I think I may have made this more complicated than necessary, but I have a key for just 'Luck' and a separate key for the phrase 'Roll Luck'.  Could you try filling out this key and seeing if it resolves the issue?

![image](https://user-images.githubusercontent.com/67403321/108010675-48264580-6fba-11eb-9aff-e8e2fb968c45.png)

**Comment by TheLastScrub** [comment]
Hey @Phenomen , my bad on this one.  I just noticed that the key I mentioned is for the label in the _header_, and I was indeed passing 'Luck' untranslated to the chat card when the roll is triggered...  Sorry about that, should be fixed in the next build.

![image](https://user-images.githubusercontent.com/67403321/111023135-212a1c00-838c-11eb-9bb1-26ef437e7679.png)
