### ISSUE TITLE
Add translation to Spanish

### ISSUE THREAD

**Issue by CthulhuRol** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#28]
Great job:
Could you add the Spanish translation as an improvement of the system?. 

I add the es.json file with the translation:
(I have added ".txt" to avoid upload the file in this message. Please, change name to "es.json")
[es.json.txt](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/files/6097136/es.json.txt)

Thanks

**Comment by TheLastScrub** [comment]
Yeah I've gotten a bit bogged down recently due to some problems swapping to a new machine, but I meant to make a new build somewhat soon anyways, so I will get this added while I'm at it.

**Comment by TheLastScrub** [comment]
Hey @CthulhuRol , I think you have the same value for both HP and WP in your translation:

![image](https://user-images.githubusercontent.com/67403321/111022121-bfff4a00-8385-11eb-9e9a-2ccddc580008.png)

I took a peak at a Spanish language character sheet, and seems like it should be 'PVOL' for WP, so I changed it to that.  Let me know if that's incorrect.

![image](https://user-images.githubusercontent.com/67403321/111022191-1bc9d300-8386-11eb-98bf-810979fbb817.png)

**Comment by CthulhuRol** [comment]
You are right.
Since I sent you the first version I have made some little changes. This is my actual version.
If I detect other errors, I will let you know.

Regarding the module:
- For your information, I have problems with combat mechanic. Damage is not reduced from target. Could you check it? please.
- There are some parts of the sheet that are not implemented in the translation. I will resume them and I will pass. If you could prepare them for translate, it will be awesome.

Thanks for your good job.

[es.json.txt](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/files/6134498/es.json.txt)

**Comment by TheLastScrub** [comment]
Hey @CthulhuRol, Thanks for your help with this!  I added your most recent translation file.  

For the damage reduction are you referring to armor?  If so I don't currently have anything implemented for taking/reducing damage based on damage, although this is on my to-do list.  If this is kind of a separate issue, could you open a new GitHub issue for it with some screenshots and description?  This will help me keep track of it.  If you mean something else, could you send me a screenshot of what you are seeing that is incorrect?

Likewise, could you send me a screenshot for anything that doesn't currently have a localization?  Or are you referring to the '?' section of the sheet?  Or are you referring to this:

![image](https://user-images.githubusercontent.com/67403321/111058246-0fa34b80-8442-11eb-8445-24b3af4ef2ff.png)

For this section, there might be a few places I could still add to the translation file.  _But_ the licensing part I worked out with Arc Dream Publishing, and I don't want to risk anything accidently changing there in translation, since that could have legal repercussions. 

Also the defaults values for this section shown below (the 'Typed' skills) are difficult to get a translation for because I've backed myself into a corner the way I implemented it.  But if this is what you are referring to, I can take another look at it to see if there is a better way to do it:

![image](https://user-images.githubusercontent.com/67403321/111058814-e4226000-8445-11eb-9a47-d07f75e5e72b.png)

**Comment by CthulhuRol** [comment]
First of all, thank you very much for implementing this system. The real job is yours. I'm just giving a serie of ideas.

1.- Regarding the problem with damage: I will create a new github issue.

2.- Lack of translation refers to the following: Two help pop-ups in the "Breakpoint" section. I attach a couple of images to you, but basically it's adding the explanation of what it is and also explaining the reset button use.

![2021-03-14 (2)](https://user-images.githubusercontent.com/80204054/111066106-a3fec400-84bd-11eb-87fc-cee004595246.png)

![2021-03-14 (3)](https://user-images.githubusercontent.com/80204054/111066119-af51ef80-84bd-11eb-8bb8-6c318a5290ea.png)

3.- I do not see any problems with the screen about author rights. Yes, it's in english, but I think it's the option. You have contacted with them and you know what kind of things could implement in this system.

4.- Regarding the last part of the skills section, I don´t know what kind of problem did you refer. I could translate it and the result is very good in may opinion.

![2021-03-14](https://user-images.githubusercontent.com/80204054/111066124-b4af3a00-84bd-11eb-8da5-1cfaf40bf026.png)

**Comment by TheLastScrub** [comment]
Thanks for splitting that combat request into a different issue.  I'll split the default type skill of 'Art' being untranslated into a different issue, and maybe revisit it in the future.

I added the missing tool tips, plus one extra key for something Uriele added, would you mind translating these three keys? 

```json 
"DG.Roll.Inhuman": "Inhuman",
"DG.Tooltip.BreakPoint": "The current breaking point, reset when current sanity falls to or below this value.  The starting breaking point is SAN - POW.",
"DG.Tooltip.BreakPointReset": "Reset breaking point to be current SAN - WP."
```
   

I think that should put me pretty close to being ready to put together a new release.

**Comment by CthulhuRol** [comment]
Of course.

"DG.Roll.Inhuman": "Inhumano",
"DG.Tooltip.BreakPoint": "El Punto de Ruptura actual, actualizar cuando la Cordura actual sea igual o inferior a este valor. El Punto de Ruptura inicial es COR - POD.",
"DG.Tooltip.BreakPointReset": "Actualizar el Punto de Ruptura al valor actual de COR - PVOL."

**Comment by TheLastScrub** [comment]
Thanks!  Let me know if you see anything else that is missing or not working.

Hopefully I can package it all up sometime later this week.  I think all I have left now is some tweaking on my one feature I'm trying to add for this release, which is the ability to choose between a few different fonts based on what kind of game you're playing.

I believe I have that mostly working now though, here is one of the new options:

![image](https://user-images.githubusercontent.com/67403321/111258566-79eef400-85da-11eb-9ae7-245c4f68ba64.png)
