### ISSUE TITLE
Request: Traditional DG styled character sheet

### ISSUE THREAD

**Issue by Randomisation** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#58]
Would it be possible to add a character/actor sheet template that is more like the official version?

**Comment by Randomisation** [comment]
One of the common complaints from my players is that the skills are read left to right, top to bottom, as opposed to being arranged as alphabetical lists.

**Comment by jshuhler** [comment]
I've also noticed this and think it would be helpful at the least. It would match the Foundry Cthulhu character sheet in going vertically instead of horizontally as well. Guessing there's a lot of overlap between players/GMs of the two systems.

**Comment by wush3** [comment]
I did make alterations to the actor template and css files for myself to make it waste less space. Did not figure out a way to change it flow vertically. (Those flexbox thingies are a pain to modify). Also no mater how hard I tried I was not able to amke the edit button part of custom skills waste less space. I attached the modified files since im not a contributor. [](url
[Delta Green modification.zip](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/files/9134129/Delta.Green.modification.zip)
)

**Comment by TheLastScrub** [comment]
Redesigning the agent sheet is probably not something that will happen any time soon, unless someone else takes a crack at it. One guy [had started this a while back](https://github.com/Djphoenix719/FVTT-DeltaGreen) actually so I had avoided making many changes to the sheets.  But I haven't heard anything from him in some time, so I kind of assume he abandoned it.

I am uncertain as well how to get things to flow vertically, and since it's still ordered alphabetically (unless you're not playing in English...), I don't really want to spend the time on it. But again, if someone put that pull request in, I'd certainly give it a look (you do not need to be a contributor to make a pull request).

As far as the CSS modifications, I don't think it looks quite right with a gap of 0px. It could probably work that way, but probably would need most/all of the existing grid lines removed or re-thought. I do generally play on a full screen monitor though, so I see why it being tall is a pain on a smaller screen. So as kind of a compromise, I set the gap to 3px instead, which I think makes the sheet quite a bit shorter, but still keeps it from feeling cluttered.  

I think I managed to merge in most of the other changes from your file as well.  This should be in the next release which will be for v10 of Foundry, which I should release shortly. I'll close this one on release, feel free to open a new issue if the new version still doesn't quite get it where you want.

![image](https://user-images.githubusercontent.com/67403321/189557785-b837a5eb-593a-4b86-975f-01cd740761ca.png)
