### ISSUE TITLE
SPECIAL TRAINING

### ISSUE THREAD

**Issue by kalmar-krazy** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#70]
Do you have any plans to include a section of the character sheet for special training? IE scuba diving or parachuting?

**Comment by TheLastScrub** [comment]
Because as far as I know special training just function like any other skill once you have them, I've always just added them as a Type Skill with category "Other" (e.g. I treat them like 'Science - Biology', except they are 'Other - Scuba Diving').

![image](https://user-images.githubusercontent.com/67403321/205456118-df2bc647-bd0e-45d8-904a-9a3f136733c1.png)

They haven't come up in my games much though, so let me know if there's a reason that doesn't fit them well in your game and I can take a look at it.

**Comment by kalmar-krazy** [comment]
only reason I really bring it up is because the training is tied to another Skill or Attribute. Meaning if one increases so should the other. So im wondering if it would be too crazy to be able to put text into the "number box" for the Special training instead

**Comment by TheLastScrub** [comment]
Ah that makes sense, now that I re-read the special training section I see they do behave differently than a skill. I might be able to implement them similar to how weapons work, in that you pick what skill/stat gets rolled when you click on it. I'll look into it.

**Comment by jalensailin** [comment]
Should be addressed in #98

**Comment by TheLastScrub** [comment]
Added by Jalen in the next release
