### ISSUE TITLE
Foundry v11 Compatibility

### ISSUE THREAD

**Issue by rnadams2** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#71]
Can we expect an update soon? I'm currently running a game in Foundry with a few others in different systems, and I'd like to install the updates for those, as well as any modules that have been updated.

**Comment by TheLastScrub** [comment]
Are you aware of any specific compatibility issues, or just asking when the system will be flagged as v11 compatible? 

Not sure exactly when I'll put out a new package, but in limited testing I've not seen any issues with the system in v11.

**Comment by rnadams2** [comment]
I've been holding out on upgrading for fear that my campaign may break. I was of the understanding (erroneously, I guess) that the DB change in the new version would cause more problems than it seems to be. I'll keep an eye out here and see if anyone brings up any issues, and upgrade eventually if nothing pops up.

Thanks!

**Comment by tompudding** [comment]
One thing I noticed is that the "Apply Skill Improvement" button seems to only work for one skill in v11. It rolls for all of them, but only one gets unchecked and increased. Clicking it n times does the trick though!

**Comment by TheLastScrub** [comment]
@tompudding Looking at it, kind of surprised the behavior on this would be any different in v10 than v11. But I think I know how to resolve it. 

@jalensailin I will make a change to _applySkillImprovements() so that all the skill updates to the actor happens in one call synchronously (as opposed to doing each skill individually in the loop). In my v11 test environment, it seems to work. 

I've seen issues like this before where because multiple updates are all happening async, only the last update goes through and wipes all the changes before it. If you think there is a more elegant way to do it though, feel free to modify it.

**Comment by jalensailin** [comment]
@TheLastScrub 

Feel free, thanks for the update and apologies for introducing an error!

**Comment by heliobolseiro** [comment]
How do I convert Delta Green to Portuguese?

**Comment by jalensailin** [comment]
@heliobolseiro it is currently not possible. can you open up an actual issue for this, rather than just a comment on an unrelated issue? Currently it isn't possible to translate fully. we would need to make it so that all of the strings are translatable. this would require some work on our end. can try to let you know when it's ready
