### ISSUE TITLE
Damage auto-roll?

### ISSUE THREAD

**Issue by lichegate** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#73]
Thank you so much for the work you've done on the system. We played last night (using V11) and everything worked great!
One question I have: Is there a way to set things so that damage rolls automatically on a success? I've seen it done that way in OSE and now I'm spoiled. 
Thanks again for all you do!
(Now I see that I probably should have put this under discussions; sorry, I'm new here...)

**Comment by TheLastScrub** [comment]
Feature requests are fine here. This request is a little tricky with the way things are currently structured, but not impossible by any means. It may take me a while to get to it though.

In the mean time, if it helps, you can drag the weapons onto the macro bar to make it easier to roll their damage. It's a bit unintuitive in that you must drag in the space in between the labels (since clicking on most of the labels does something).

**Comment by jalensailin** [comment]
> It's a bit unintuitive in that you must drag in the space in between the labels (since clicking on most of the labels does something).

This should be fixed with my most recent changes. You should be able to drag from anywhere on the item in the actor's sheet now

**Comment by TheLastScrub** [comment]
In the next release, the item macro can do this (thanks to @jalensailin's refactor of the roll logic) so I will close this one out. Example:

Drag item onto bar to get macro:

![image](https://github.com/user-attachments/assets/aa3a2361-9046-4032-87d6-a07618578734)

Clicking on the macro (on a successful test) gives:

<img width="219" alt="image" src="https://github.com/user-attachments/assets/6d71a855-9f68-496f-8d9d-184cc232b719">
