### ISSUE TITLE
v11 LevelDB databases missing in zip

### ISSUE THREAD

**Issue by rikmarais** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#82]
Since the package is minimum compatibility v11, could I please request that v11 LevelDB databases be included in upcoming releases?

This would allow users on the Forge to use the Bazaar version of the v11 system.
Currently, they need to install the package as a custom package so that Foundry can have write access in the directory (which exists in the Forge Bazaar) to migrate the databases from .db files to LevelDB databases.

![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/34374883/2ca8c606-5237-40ff-9395-a28467ab6e9e)

There may be a valid reason for keeping the v10 databases, though. If is the case and this module doesn't aim to include the v11 databases in the zip, instead relying on Foundry's v10 -> v11 migration to LevelDB when the system is first accessed after an update, please let me know! 🙏

**Comment by TheLastScrub** [comment]
I thought that letting Foundry run the upgrade against the v10 databases seemed to work well for my Windows Electron setup as well as my self-hosted Ubuntu server setup. But I don't use the Forge so that wasn't a scenario I tested. I did have one other issue from a Forge user, but they had a workaround for it.

The only real reason I kept the v10 databases was that the v11 database files are constantly changing, which was a bit annoying from a GIT perspective. I can look into the right way to include the v11 files instead, since I was not shooting for backwards compatibility with v10 anyways.

**Comment by TheLastScrub** [comment]
@rikmarais I'm not that familiar with the Forge, could you try the new version that just released (v1.2.6) and see if it resolves your issues? @jalensailin  has changed our packaging process so that hopefully now we will just have the v11 databases for compendia automatically deployed.

**Comment by rikmarais** [comment]
This fix is brilliant 🙏 Thank you and all contributors for your efforts. Testing is all green on our side.
