### ISSUE TITLE
On-the-fly modifiers

### ISSUE THREAD

**Issue by ericcberg** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#86]
Am I crazy, or did the ability to right-click and get the chance to add a one-off modifier to the roll disappear?

**Comment by TheLastScrub** [comment]
You can still shift-click to get the modifier dialogue. 

I think you could previously also right click to get it on everything but the luck roll, and it does look to me like this possibly got lost in our roll refactor that we did in the latest version. I'd have to dig in a bit to confirm, since I usually shift-click.

We did change the logic a bit to try to avoid having so many miss-clicks triggering unwanted rolls when opening a character sheet. I have a hunch this may have caused it.

**Comment by TheLastScrub** [comment]
@jalensailin I think this was why I was using 'mousedown' previously haha, knew we'd figure it out sooner or later. I think looking into it, the better way to do it though is to bind the 'contextmenu' event which grabs the right click event more naturally. I will test it a bit more, but a quick test seemed to get this working again by just adding this on line 222:

![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/67403321/2e4afe86-4424-4451-9eaf-bcd56f4f4581)

**Comment by TheLastScrub** [comment]
Should be fixed in latest (v.1.3.2), feel free to re-open the issue if not.
