### ISSUE TITLE
importing monsters, spells, etc. from Open Mythos

### ISSUE THREAD

**Issue by stories-with-dice** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#92]
Hello,

Have you considered importing the entries from Open Mythos?

https://cthulhueternal.com/open-mythos/

These are the public domain elements of the Mythos, statted for Cthulhu Eternal (which is a free OGL clone of CoC/DG).

The stats are mostly compatible with DG, so could be imported easily into the schema.

If it's okay to do and you don't have time, I could do it.

**Comment by TheLastScrub** [comment]
DG is purging all the OGL references it had, so I'm a bit leery of adding anything where I'd have to re-include the OGL license. I do think it is an interesting idea though. Perhaps it could be made as a standalone module that includes everything a a compendium pack when you enable it? I think that would be a little cleaner way to do it.

**Comment by jalensailin** [comment]
I agree that a fan-made stand-alone module is more appropriate for something like this. It seems very cool but since it doesn't come directly from DG I think it would be weird for us to include with the system. I'd say, if you want to make an external module within the license/rights of the Cthulu Eternal folks, you should go for it. Will close this issue.

**Comment by jalensailin** [comment]
Closing this issue but if you do want to discuss more with us, this would probably be more appropriate as a [Discussion](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/discussions). We do appreciate the idea and look forward to any module you end up making :)
