### ISSUE TITLE
Checkbox on typed skills

### ISSUE THREAD

**Issue by ericcberg** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#99]
There is no checkbox to note failures for typed skills.

**Comment by TheLastScrub** [comment]
Thanks for letting me know about this, I see the issue. When @jalensailin moved this to a partial template during the last round of updates, the context of the handlebars expression changed. The fix is just to add ../ in front of the property to reference the parent context instead. I will check this in and make a new build for it sometime this week.

**Comment by ericcberg** [comment]
Awesome. You folks are doing amazing work.

**Comment by TheLastScrub** [comment]
Should be resolved in v1.4.1
